using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    /// <inheritdoc />
    public partial class first : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Games') THEN CREATE TABLE \"Games\" (" +
                                 "\"GameId\" integer GENERATED BY DEFAULT AS IDENTITY, " +
                                 "\"GameName\" text NOT NULL, " +
                                 "CONSTRAINT \"PK_Games\" PRIMARY KEY (\"GameId\")); END IF; END $$;");

            migrationBuilder.Sql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Users') THEN CREATE TABLE \"Users\" (" +
                                 "\"UserId\" integer GENERATED BY DEFAULT AS IDENTITY, " +
                                 "\"UserName\" text NOT NULL, " +
                                 "\"UserPassword\" text NOT NULL, " +
                                 "\"UserEmail\" text NOT NULL, " +
                                 "\"IsAdmin\" boolean NOT NULL, " +
                                 "CONSTRAINT \"PK_Users\" PRIMARY KEY (\"UserId\")); END IF; END $$;");

            migrationBuilder.Sql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Friendships') THEN CREATE TABLE \"Friendships\" (" +
                                 "\"FriendshipId\" integer GENERATED BY DEFAULT AS IDENTITY, " +
                                 "\"User1Id\" integer NOT NULL, " +
                                 "\"User2Id\" integer NOT NULL, " +
                                 "CONSTRAINT \"PK_Friendships\" PRIMARY KEY (\"FriendshipId\")); " +
                                 "ALTER TABLE \"Friendships\" ADD CONSTRAINT \"FK_Friendships_Users_User1Id\" FOREIGN KEY (\"User1Id\") REFERENCES \"Users\" (\"UserId\") ON DELETE RESTRICT; " +
                                 "ALTER TABLE \"Friendships\" ADD CONSTRAINT \"FK_Friendships_Users_User2Id\" FOREIGN KEY (\"User2Id\") REFERENCES \"Users\" (\"UserId\") ON DELETE RESTRICT; END IF; END $$;");

            migrationBuilder.Sql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Sessions') THEN CREATE TABLE \"Sessions\" (" +
                                 "\"SessionId\" integer GENERATED BY DEFAULT AS IDENTITY, " +
                                 "\"UserId\" integer NOT NULL, " +
                                 "\"GameId\" integer NOT NULL, " +
                                 "\"GameName\" text NOT NULL, " +
                                 "\"Start\" timestamp with time zone NOT NULL, " +
                                 "\"End\" timestamp with time zone NOT NULL, " +
                                 "CONSTRAINT \"PK_Sessions\" PRIMARY KEY (\"SessionId\")); " +
                                 "ALTER TABLE \"Sessions\" ADD CONSTRAINT \"FK_Sessions_Games_GameId\" FOREIGN KEY (\"GameId\") REFERENCES \"Games\" (\"GameId\") ON DELETE CASCADE; " +
                                 "ALTER TABLE \"Sessions\" ADD CONSTRAINT \"FK_Sessions_Users_UserId\" FOREIGN KEY (\"UserId\") REFERENCES \"Users\" (\"UserId\") ON DELETE CASCADE; END IF; END $$;");

            migrationBuilder.Sql(@"DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Friendships_User1Id') THEN 
                    CREATE INDEX ""IX_Friendships_User1Id"" ON ""Friendships"" (""User1Id"");
                END IF; 
            END $$;");

            migrationBuilder.Sql(@"DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Friendships_User2Id') THEN 
                    CREATE INDEX ""IX_Friendships_User2Id"" ON ""Friendships"" (""User2Id"");
                END IF; 
            END $$;");

            migrationBuilder.Sql(@"DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Sessions_GameId') THEN 
                    CREATE INDEX ""IX_Sessions_GameId"" ON ""Sessions"" (""GameId"");
                END IF; 
            END $$;");

            migrationBuilder.Sql(@"DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Sessions_UserId') THEN 
                    CREATE INDEX ""IX_Sessions_UserId"" ON ""Sessions"" (""UserId"");
                END IF; 
            END $$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Friendships");

            migrationBuilder.DropTable(
                name: "Sessions");

            migrationBuilder.DropTable(
                name: "Games");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
